# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Respinar\GlossaryBundle\:
        resource: ../src/
        exclude: ../src/DependencyInjection

